const data = [
  {name: "Berkshire", country: "UK", count: 21, minYear: 1812},
  {name: "Billund", country: "Denmark", count: 1, minYear: 1924},
  {name: "Buckinghamshire", country: "UK", count: 1, minYear: 2004},
  {name: "Cambridgeshire", country: "UK", count: 15, minYear: 1838},
  {name: "Copenhagen", country: "Denmark", count: 3, minYear: 1756},
  {name: "Denmark", country: "null", count: 4, minYear: 1756},
  {name: "East_Sussex", country: "UK", count: 6, minYear: 1841},
  {name: "Hertfordshire", country: "UK", count: 16, minYear: 1665},
  {name: "Istanbul", country: "Turkey", count: 8, minYear: 1858},
  {name: "Lisbon", country: "Portugal", count: 4, minYear: 1865},
  {name: "London", country: "UK", count: 217, minYear: 1580},
  {name: "Manchester", country: "UK", count: 3, minYear: 1832},
  {name: "Oxfordshire", country: "UK", count: 24, minYear: 1879},
  {name: "Perm", country: "Russia", count: 1, minYear: 2010},
  {name: "Porto", country: "Portugal", count: 2, minYear: 1892},
  {name: "Portugal", country: "null", count: 7, minYear: 1757},
  {name: "Russia", country: "null", count: 1, minYear: 2010},
  {name: "Sintra", country: "Portugal", count: 1, minYear: 1757},
  {name: "Somerset", country: "UK", count: 4, minYear: 1706},
  {name: "Surrey", country: "UK", count: 10, minYear: 1880},
  {name: "Turkey", country: "null", count: 8, minYear: 1858},
  {name: "UK", country: "null", count: 225, minYear: 1580},
  {name: "World", country: "null", count: 228, minYear: 1580},
]
