const data = [
  { "id": "m-birmngham-stoke-on-trent", "name": "Midlands: Birmingham & Stoke-on-Trent", "count": 5 },
  { "id": "m-leamington-spa-birmingham", "name": "Midlands: Leamington Spa & Birmingham", "count": 3 },
  { "id": "m-leicester-birmingham", "name": "Midlands: Leicester & Birmingham", "count": 3 },
  { "id": "m-leicester-derby", "name": "Midlands: Leicester & Derby", "count": 5 },
  { "id": "m-milton-keynes-northampton", "name": "Midlands: Milton Keynes & Northampton", "count": 5 },
  { "id": "m-northampton-coventry", "name": "Midlands: Northampton & Coventry", "count": 6 },
  { "id": "m-oxford-banbury", "name": "Midlands: Oxford & Banbury", "count": 7 },
  { "id": "m-peterborough-kings-lynn", "name": "Midlands: Peterborough & Kings Lynn", "count": 1 },
  { "id": "m-peterborough-leicester", "name": "Midlands: Peterborough & Leicester", "count": 5 },
  { "id": "m-wolverhampton-stafford", "name": "Midlands: Wolverhampton & Stafford", "count": 1 },
  { "id": "m-worcester", "name": "Midlands: Worcester", "count": 1 },
  { "id": "me-audley-end-huntingdon", "name": "East Midlands: Audley End & Huntingdon", "count": 6 },
  { "id": "me-colchester-braintree", "name": "East Midlands: Colchester & Braintree", "count": 5 },
  { "id": "me-colchester-ipswich", "name": "East Midlands: Colchester & Ipswich", "count": 3 },
  { "id": "me-ipswich-cambdridge", "name": "East Midlands: Ipswich & Cambridge", "count": 5 },
  { "id": "me-norwich-1", "name": "East Midlands: Norwich (east)", "count": 4 },
  { "id": "me-norwich-2", "name": "East Midlands: Norwich (north)", "count": 2 },
  { "id": "n-leeds-1", "name": "North: Leeds", "count": 7 },
  { "id": "n-leeds-2", "name": "North: Leeds (north)", "count": 2 },
  { "id": "n-leeds-manchester", "name": "North: Leeds & Manchester", "count": 6 },
  { "id": "n-sheffield", "name": "North: Sheffield", "count": 5 },
  { "id": "n-sheffield-stockport", "name": "North: Sheffield & Stockport", "count": 6 },
  { "id": "ne-doncaster", "name": "North East: Doncaster", "count": 3 },
  { "id": "ne-hull-york", "name": "North East: Hull & York", "count": 3 },
  { "id": "ne-liverpool", "name": "North East: Liverpool", "count": 5 },
  { "id": "ne-middlesbrough", "name": "North East: Middlesbrough", "count": 1 },
  { "id": "ne-newcastle-upon-tyne", "name": "North East: Newcastle upon Tyne", "count": 5 },
  { "id": "ne-york", "name": "North East: York", "count": 1 },
  { "id": "nw-chester", "name": "North West: Chester", "count": 5 },
  { "id": "nw-manchester", "name": "North West: Manchester", "count": 9 },
  { "id": "nw-penrith", "name": "North West: Penrith", "count": 3 },
  { "id": "nw-preston-liverpool", "name": "North West: Preston & Liverpool", "count": 10 },
  { "id": "nw-preston-manchester-1", "name": "North West: Preston & Manchester (west)", "count": 6 },
  { "id": "nw-preston-manchester-2", "name": "North West: Preston & Manchester (north-east)", "count": 5 },
  { "id": "sw-barnstaple", "name": "South West: Barnstaple", "count": 1 },
  { "id": "sw-bath-swindon", "name": "South West: Bath & Swindon", "count": 7 },
  { "id": "sw-bournemouth", "name": "South West: Bournemouth", "count": 3 },
  { "id": "sw-bristol-bath", "name": "South West: Bristol & Bath", "count": 8 },
  { "id": "sw-castle-cary-bath", "name": "South West: Castle Cary & Bath", "count": 8 },
  { "id": "sw-exeter", "name": "South West: Exeter", "count": 4 },
  { "id": "sw-plymouth", "name": "South West: Plymouth", "count": 2 },
  { "id": "sw-portsmouth", "name": "South West: Portsmouth", "count": 4 },
  { "id": "sw-salisbury", "name": "South West: Salisbury", "count": 5 },
  { "id": "sw-southampton", "name": "South West: Southampton", "count": 3 },
  { "id": "sw-stroud-didcot", "name": "South West: Stroud & Didcot", "count": 5 },
  { "id": "sw-taunton", "name": "South West: Taunton", "count": 3 },
  { "id": "sw-yeovil", "name": "South West: Yeovil", "count": 3 },
]
